<a href="https://colab.research.google.com/github/nsx270/ExerciciosBibliotecaPython/blob/main/ExerciciosBibliotecas_Python_PedroHenriqueToledo_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios de NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

In [ ]:
import numpy as np
array = np.random.randint(10, 100, 50);
print(array);

#Uso de randint pra definir o limite de 10 a 101 e tamanho de 50 itens

[72 92 44 37 49 54 90 18 58 95 32 17 64 83 40 33 40 56 38 80 45 65 67 23
 96 47 69 91 10 12 51 28 62 42 11 61 89 41 97 60 68 51 53 98 97 75 27 11
 50 90]


2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última
linha.

In [ ]:
import numpy as np
matriz = np.random.randint(1, 16, (4, 4));
print(matriz);
print("Linha extraída: ")
print(matriz[-1]);

#Crio um arrange 1 a 16, redimensiono para 4x4 e pego o indice -1 para a última linha

[[11  8 14  9]
 [11 10  6 14]
 [ 7  9  5  2]
 [ 7 15 14  9]]
Linha extraída: 
[ 7 15 14  9]


3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
à 10ª posição por 1.

In [ ]:
import numpy as np
array = np.zeros(15);
array[4:10] = 1;
print(array);

#Lembrar que em Python a quinta posição é o indice 4 e vai ate o indice 10

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e
a moda dos valores.

In [ ]:
import numpy as np
from scipy import stats
array = np.random.randint(1, 100, size=100);
mediana = np.median(array);
moda = stats.mode(array, kleepdims=False).mode
print("Mediana: ", mediana, "Moda: ", moda)

#Para a moda, como o numpy náo tem função nativa, uso o scipy stats.

Mediana:  14.0
Moda:  6


5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por -3.

In [ ]:
import numpy as np
array = np.random.randint(1, 100, size=20);
print("Array original: ",array);
array[array % 3 == 0] = -3;
print("Array modificado: ",array)

#Uso a máscara booleana com o operador de resto da divisão

Array original:  [ 4 38 72 84 47 68 39 13 87 60  1 70 18 95  2 88 46 81 40 69]
Array modificado:  [ 4 38 -3 -3 47 68 -3 13 -3 -3  1 70 -3 95  2 88 46 -3 40 -3]


6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna

In [ ]:
import numpy as np
matriz = np.random.rand(5 ,5)
print(matriz)
soma = np.sum(matriz, axis=0)
print(soma)

#Axis = 0, soma ao longo das linhas, retornando a soma de cada coluna

[[0.97276368 0.34910391 0.67382429 0.30256359 0.33799296]
 [0.51922884 0.98211143 0.87986959 0.65265773 0.4160899 ]
 [0.25167075 0.61506025 0.59720099 0.65629678 0.76702606]
 [0.70748005 0.78927431 0.68489475 0.96959043 0.3334028 ]
 [0.31993697 0.12781749 0.26954051 0.39476476 0.97257952]]
[2.77108029 2.8633674  3.10533014 2.97587328 2.82709124]


7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [ ]:
import numpy as np
array1 = np.random.rand(10);
array2 = np.random.rand(10);
correlacao_mt = np.corrcoef(array1, array2);
correlacao = correlacao_mt[0,1];
print("Matriz de correlação: \n", correlacao_mt);
print("Correlação específica: \n", correlacao);

#Uso de corrcoef que retorna a matriz de correlação e pego a posição [0,1]

Matriz de correlação: 
 [[1.         0.51173315]
 [0.51173315 1.        ]]
Correlação específica: 
 0.5117331543481943


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.

In [ ]:
import numpy as np
matriz = np.random.randint(1, 10, size=(3,3));
matriz_quadrado = matriz**2;
print(matriz_quadrado)

#Elevar ao quadrado direto na matriz

[[49 64  9]
 [81 25 16]
 [64 25  1]]


9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.

In [ ]:
import numpy as np
array = np.random.rand(10) * 50
array_norm = (array - np.min(array)) / (np.max(array) - np.min(array))
print(array_norm)

#Formula do min-max: (x - min) / (max - min)

10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores
crescentes de 1 a 6.

In [ ]:
import numpy as np
matriz = np.eye(6)
np.fill_diagonal(matriz, np.arange(1,7))
print(matriz)

#Uso np.eye(6) e altero a diagonal com np.fill_diagonal

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


11. Gere um array de 100 números inteiros e encontre o valor que mais se
repete no array.

In [ ]:
import numpy as np
array = np.random.randint(1,20,size=100)
valores, contagens = np.unique(array, return_counts=True)
mais_repetido = valores[np.argmax(contagens)]
print("Valor que mais se repete é: ",mais_repetido)

#Np.unique com return_counts=True me dá valores e a quantidade de vezes que ele aparece

Valor que mais se repete é:  10


12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

In [ ]:
import numpy as np
matriz = np.zeros((4,4))
np.fill_diagonal(matriz, 7)
print(matriz)

#Criando uma matriz de zeros 4x4 e atribuindo 7 na diagonal

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


13. Crie um array contendo os 10 primeiros números pares e calcule sua soma
cumulativa.

In [ ]:
import numpy as np
pares = np.arange(2,22,2)
soma_cum = np.cumsum(pares)
print(soma_cum)

#Os 10 primeiros pares positivos de 2 a 20

[  2   6  12  20  30  42  56  72  90 110]


14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimentos e encontre a média das diferenças

In [ ]:
import numpy as np
arr_a = np.random.rand(15)
arr_b = np.random.rand(15)
diferenca = arr_a = arr_b
media_dif  = np.mean(diferenca)
print("Média das diferenças: ",media_dif)

#Subtração direta dos arrays e aplica o mean

Média das diferenças:  0.54231789320763


15. Gere um array contendo 20 números e substitua todos os valores maiores
que 50 por 50.

In [ ]:
import numpy as np
array = np.random.randint(1, 100, size=20)
array[array > 50] =50
print(array)

#Filtro booleano direto para atribuir o limite

[26 31 48 47 50  1 50  8 24 13 50 13 50 46 31 50 50 50  9 41]


16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.

In [ ]:
import numpy as np
array = np.arange(12)
matriz = array.reshape(3,4)
print(matriz)

#Array de 12 elementos reformatado com reshape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada
valor por sua posição na matriz.

In [ ]:
import numpy as np
matriz = np.random.randint(1,10,size=(4,4))
resultado = np.zeros((4,4))
for i in range(4):
    for j in range (4):
      resultado17[i,j] = matriz[i,j] * (i * j)
print(resultado)

#Uso dos indices i e j para multiplicar pelo número da linha e coluna correspondente

18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 5 por 0.

In [ ]:
import numpy as np
array = np.random.randint(1,101,size=10)
array[array % 5==0] = 0
print(array)

#Máscara booleana procurando resto de zero na divisão por 5

19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o
ângulo entre eles (produto escalar normalizado).

In [ ]:
import numpy as np
v1 = np.random.randint(1,10,size=20)
v2 = np.random.randint(1,10,size=20)
cos_theta = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
angulo = np.arccos(np.clip(cos_theta, -1.0, 1.0))
print("Angulo em radianos: ",angulo)

#Cálculo da norma com linalg.norm e produto escalar com dot, aplicando arccos para achar o ângulo em radianos

Angulo em radianos:  0.6376832794474321


20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada
linha.

In [ ]:
import numpy as np
matriz = np.random.randint(1,50,size=(4,4))
min_linhas = np.min(matriz, axis=1)
print(matriz)
print("Mínimos por linha: ",min_linhas)

#Min com axis=1 varre ao longo das colunas, pegando o menor de cada linha

[[35 34 11 27]
 [23 49 33 18]
 [45 34 22  6]
 [45 40 48 44]]
Mínimos por linha:  [11 18  6 40]


# Exercícios de SciPy

1. Calcule a integral da função f(x) = x^2 * sin(x) no intervalo de 0 a pi.

In [ ]:
def f1(x):
  return (x**2) * np.sin(x)

#Defino a função integral e uso integrate.quad

2. Resolva a equação diferencial dy/dx = x - y com y(0) = 1, no intervalo de 0 a 10.

In [ ]:
def edo2(x,y):
  return x - y

#Defino a equação diferencial e uso solve_ivp

3. Encontre as raízes da função f(x) = x^4 - 3x^3 + 2 utilizando SciPy.

In [ ]:
coefs = [1, -3, 0, 0, 2]
raizes = np.roots(coefs)
print("Raízes: ",raizes)

#Como é um polimonio x^4 - 3x^3 + 0x^2 + 0x + 2, uso np.roots

4. Use a função de otimização de SciPy para maximizar f(x) = -x^2 + 4x + 1

In [ ]:
def f4(x):
  return -(-x**2 + 4 * x + 1)
res4 = optimize.minimize(f4, 0)
print("Ponto de máximo (x):", res4.x[0])

# Para maximizar com minimize, passo a função com o sinal invertido

5. Calcule a transformada de Fourier de um sinal composto de sin(2*pi*t) e cos(4*pi*t).

In [ ]:
t5 = np.linspace(0, 1, 100)
sinal5 = np.sin(2 * np.pi * t5) + np.cos(4 * np.pi * t5)
fft5 = fft.fft(sinal5)
print(fft5)

# Gerando um sinal simples no tempo t e aplicando fft

6. Encontre a matriz inversa de uma matriz 5x5 de números aleatórios.

In [ ]:
matriz6 = np.random.rand(5, 5)
inv6 = linalg.inv(matriz6)
print(inv6)

# Uso linalg.inv da biblioteca scipy.linalg

7. Use a função de interpolação cúbica de SciPy para interpolar os dados (0,0), (1, 2), (2, 3), (3, 5), (4, 4).

In [ ]:
x7 = np.array([0, 1, 2, 3, 4])
y7 = np.array([0, 2, 3, 5, 4])
f_interp7 = interpolate.interp1d(x7, y7, kind="cubic")
print("Valores interpolados em 1.5 e 2.5:", f_interp7([1.5, 2.5]))

# Separo x e y, e crio a função com interp1d usando kind='cubic'

8. Resolva o sistema de equações 3x + 2y = 5 e x + 4y = 6.

In [ ]:
A8 = np.array([[3, 2], [1, 4]])
B8 = np.array([5, 6])
sol8 = linalg.solve(A8, B8)
print("Solução [x, y]:", sol8)

# Monto a matriz A com coeficientes e B com as respostas, depois linalg.solve

9. Ajuste uma curva quadrática aos pontos (1, 2), (2, 4), (3, 5), (4, 7), (5, 8).

In [ ]:
def quad9(x, a, b, c):
  return a * x**2 + b * x + c
x9 = np.array([1, 2, 3, 4, 5])
y9 = np.array([2, 4, 5, 7, 8])
params9, _ = optimize.curve_fit(quad9, x9, y9)
print("Parâmetros [a, b, c]:", params9)

# Modelo da parábola a*x^2 + b*x + c e uso curve_fit

10. Calcule a integral dupla da função f(x,y) = xy + x^2 no intervalo [0,2] para x e [0,1] para y.

In [ ]:
def f10(y, x):
  return x * y + x**2
res10, _ = integrate.dblquad(f10, 0, 2, lambda x: 0, lambda x: 1)
print("Integral dupla:", res10)

# dblquad exige a função recebendo (y, x) e os limites de y sendo funções

11. Encontre os autovalores e autovetores de uma matriz 4x4 de números inteiros aleatórios.

In [ ]:
matriz11 = np.random.randint(1, 10, size=(4, 4))
autovalores, autovetores = linalg.eig(matriz11)
print("Autovalores:", autovalores)

# Uso linalg.eig que me devolve ambos

12. Resolva a equação e^x - x^2 = 0 para encontrar a raiz mais próxima de x = 1.

In [ ]:
def eq12(x):
  return np.exp(x) - x**2
res12 = optimize.root(eq12, 1)
print("Raiz próxima de 1:", res12.x)

# Uso root do módulo optimize

13. Calcule o determinante de uma matriz 6x6 de números aleatórios entre -10 e 10.

In [ ]:
matriz13 = np.random.uniform(-10, 10, size=(6, 6))
det13 = linalg.det(matriz13)
print("Determinante:", det13)

# Uso linalg.det

14. Utilize a função de otimização multivariada para minimizar f(x,y) = (x-2)^2 + (y-3)^2.

In [ ]:
def f14(v):
  return (v[0] - 2) ** 2 + (v[1] - 3) ** 2
res14 = optimize.minimize(f14, [0, 0])
print("Mínimo em [x, y]:", res14.x)

# Passo o vetor v com os parâmetros x e y

15. Calcule a transformada de Fourier inversa de um sinal complexo gerado aleatoriamente.

In [ ]:
sinal_complexo = np.random.rand(10) + 1j * np.random.rand(10)
ifft15 = fft.ifft(sinal_complexo)
print(ifft15)

# Uso fft.ifft

16. Resolva a equação diferencial de segunda ordem d^2y/dx^2 + y = 0, com condições iniciais y(0) = 1 e y'(0) = 0

In [ ]:
def edo16(x, y):
  return [y[1], -y[0]]
sol16 = integrate.solve_ivp(
    edo16, [0, 10], [1, 0], t_eval=np.linspace(0, 10, 20)
)
print("Valores de y:", sol16.y[0])

# Transformo em sistema de 1ª ordem: y0' = y1; y1' = -y0

17. Encontre a raiz cúbica de 27 utilizando SciPy.

In [ ]:
def eq17(x):
  return x**3 - 27
res17 = optimize.fsolve(eq17, 1)
print("Raiz cúbica de 27:", res17[0])

# Posso achar a raiz de x^3 - 27 = 0 usando optimize.cbrt do scipy ou fsolve

18. Interpole os valores de uma função f(x) = x^2 nos pontos [1,2,3,4,5] utilizando spline cúbica.

In [ ]:
x18 = np.array([1, 2, 3, 4, 5])
y18 = x18**2
cs18 = interpolate.CubicSpline(x18, y18)
print("Interpolação no ponto 2.5:", cs18(2.5))

# Uso CubicSpline do módulo interpolate

19. Realize a transformada de Fourier de um sinal discreto composto de senos e cossenos.

In [ ]:
t19 = np.linspace(0, 1, 64)
sinal19 = np.sin(2 * np.pi * t19) + np.cos(3 * np.pi * t19)
fft19 = fft.fft(sinal19)
print(fft19)

# t de 0 a 1 e aplica a fft

20. Resolva um sistema de equações lineares com três variáveis utilizando SciPy.

In [ ]:
A20 = np.array([[1, 2, 3], [2, -1, 1], [3, 0, -1]])
B20 = np.array([9, 8, 3])
sol20 = linalg.solve(A20, B20)
print("Solução de [x, y, z]:", sol20)

# Exemplo de sistema Ax = B de tamanho 3x3

# Exercícios de Pandas