<a href="https://colab.research.google.com/github/nsx270/ExerciciosBibliotecaPython/blob/main/ExerciciosBibliotecas_Python_PedroHenriqueToledo_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios de NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

In [25]:
import numpy as np
array = np.random.randint(10, 100, 50);
print(array);

[14 77 70 31 68 93 67 10 41 33 78 98 79 54 62 58 75 81 66 96 84 85 67 79
 25 29 81 60 63 97 50 73 73 93 55 32 23 51 97 85 73 54 12 76 22 10 35 11
 76 27]


2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última
linha.

In [ ]:
import numpy as np
matriz = np.random.randint(1, 16, (4, 4));
print(matriz);
print("Linha extraída: ")
print(matriz[-1]);

[[ 1 14  2  1]
 [ 8 12  3  6]
 [14  6 10  5]
 [ 9  6  4  8]]
Linha extraída: 
[9 6 4 8]


3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
à 10ª posição por 1.

In [ ]:
import numpy as np
array = np.zeros(15);
array[4:10] = 1;
print(array);

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e
a moda dos valores.

In [13]:
import numpy as np
array = np.random.randint(1, 30, size=100);
mediana = np.median(array);
moda = np.bincount(array).argmax();
print("Mediana: ", mediana);
print("Moda: ", moda);

Mediana:  15.0
Moda:  10


5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por -3.

In [15]:
import numpy as np
array = np.random.randint(1, 100, size=20);
print("Array original: ",array);
array[array % 3 == 0] = -3;
print("Array modificado: ",array)


Array original:  [32 36 57 24 26 79  6  8 23 27 32 78 39 64 89 62 67 50 15 59]
Array modificado:  [32 -3 -3 -3 26 79 -3  8 23 -3 32 -3 -3 64 89 62 67 50 -3 59]


6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna

In [16]:
import numpy as np
matriz = np.random.rand(5 ,5)
print(matriz)
soma = np.sum(matriz, axis=0)
print(soma)

[[0.97276368 0.34910391 0.67382429 0.30256359 0.33799296]
 [0.51922884 0.98211143 0.87986959 0.65265773 0.4160899 ]
 [0.25167075 0.61506025 0.59720099 0.65629678 0.76702606]
 [0.70748005 0.78927431 0.68489475 0.96959043 0.3334028 ]
 [0.31993697 0.12781749 0.26954051 0.39476476 0.97257952]]
[2.77108029 2.8633674  3.10533014 2.97587328 2.82709124]


7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [24]:
import numpy as np
array1 = np.random.rand(10)
array2 = np.random.rand(10)
correlacao_mt = np.corrcoef(array1, array2)
correlacao = correlacao_mt[0,1]
print("Matriz de correlação: \n", correlacao_mt)
print("Correlação específica: \n", correlacao)

Matriz de correlação: 
 [[ 1.         -0.07317472]
 [-0.07317472  1.        ]]
Correlação específica: 
 -0.07317472116159039


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.

In [ ]:
import numpy as np

9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.

10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores
crescentes de 1 a 6.

11. Gere um array de 100 números inteiros e encontre o valor que mais se
repete no array.

12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

13. Crie um array contendo os 10 primeiros números pares e calcule sua soma
cumulativa.

14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimentos e encontre a média das diferenças

15. Gere um array contendo 20 números e substitua todos os valores maiores
que 50 por 50.

16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.

17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada
valor por sua posição na matriz.

18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 5 por 0.

19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o
ângulo entre eles (produto escalar normalizado).

20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada
linha.